apiVersion: v1
baseDomain: cmpf.schwarz 
proxy:
  httpProxy: http://192.168.0.1:3128
  httpsProxy: http://192.168.0.1:3128
  noProxy: localhost,127.0.0.1,192.168.0.0/24,.cmpf.schwarz
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: sandbox-ocp4
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
fips: false 
pullSecret: '{"auths":"XXXX"}'
sshKey: 'ssh-rsa YYYY' 
